variables:
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  PROD_LABEL: '1.0.0'
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

image: maven:3-openjdk-17

stages:
  - build_and_test
  - deploy_test_env
  - deploy_prod_env

cache:
  paths:
    - .m2/repository

.verify:
  stage: build_and_test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'

verify:jdk17:
  extends:
    - .verify

deploy_to_test_env_aws_eb:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy_test_env
  environment:
    name: test
    url: "http://testkoopa.us-east-2.elasticbeanstalk.com/"
  only:
    - main
  artifacts:
    paths:
      - target/
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - aws elasticbeanstalk create-application-version --application-name "Test Koopa" --version-label "$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID"
    - aws elasticbeanstalk update-environment --application-name "Test Koopa" --environment-name "TestKoopa-env" --version-label "$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID"

deploy_to_prod_env_aws_eb:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy_prod_env
  environment:
    name: production
    url: "http://koopa.us-east-2.elasticbeanstalk.com/"
  only:
    - main
  artifacts:
    paths:
      - target/
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - aws elasticbeanstalk create-application-version --application-name "Project Koopa" --version-label "$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID"
    - aws elasticbeanstalk update-environment --application-name "Project Koopa" --environment-name "ProjectKoopa-env-3" --version-label "$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID"


